# 
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
lastannouncementtime: 1526407945
lastseentime: 1526407945
test: false
gameroles:
- Minecraft
- Overwatch
- CAH
- Golf
- Civ
- Chivalry
- WoW
- Terraria
- GMOD
- Insurgency
- GW2
- DnD
- Battlefield
- Titanfall
- AoE
- Factorio
- CSGO
- TF2
- Helldivers
- R6Siege
- Hearthstone
- LoL
- Rust
- Starbound
- Halo
- FTB
- Rocket League
- GTA V
- Guns of Icarus
- The Forest
- Mass Effect
- For Honor
- PUBG
- Vanilla WoW
- HOI4
- Lethal League
serverup: true
