#********************************************************************************************************#
#*****************************************  EnchantLimit Settings  **************************************#

#Should this plugin apply changes to enchantments on enchanting-tables, anvils and villager trades?
Anvil_Limiter_Enabled: false
Enchanting_Table_Limiter_Enabled: false
Villager_Limiter_Enabled: false

#Should OP's have all beneficial enchantments by default?
Default_OP_Permissions: false


#********************************************************************************************************#
#*****************************************  Message Customization  **************************************#

# What message should be displayed when an enchantment is limited at an enchantment table? (Disable message by setting to: null)
# Note: %enc is where the enchantment type is inserted, %olv is where the original level is inserted and %nlv is where the new level is inserted.
# Use & for colour codes, colour codes available here: http://goo.gl/4DcswV
Message_Level_Downgraded_Table: "&5 Enchantment %enc level changed from %olv to %nlv."

# What message should be displayed when an enchantment is limited at an anvil? (Disable message by setting to: null)
Message_Level_Downgraded_Anvil: "&5 Enchantment %enc level changed from %olv to %nlv." # null

# What message should be displayed when an enchantment is limited when trading with a villager? (Disable message by setting to: null)
Message_Level_Downgraded_Trade: "&5 Enchantment %enc level changed from %olv to %nlv."

# What message should be displayed when an enchantment is increased at an enchantment table? (Disable message by setting to: null)
Message_Level_Upgraded_Table: "&5 You were lucky! Enchantment %enc level increased from %olv to %nlv."

# What message should be displayed when an enchantment is increased at an anvil? (Disable message by setting to: null)
Message_Level_Upgraded_Anvil: null

# What message should be displayed when an enchantment is increased when trading with a villager? (Disable message by setting to: null)
Message_Level_Upgraded_Trade: "&5 You were lucky! Enchantment %enc level increased from %olv to %nlv."

# What message should be displayed when an enchantment is removed (level set to 0) at an enchantment table? (Disable message by setting to: null)
Message_Enchantment_Removed_Table: "&5 Enchantment %enc not added!."

# What message should be displayed when an enchantment is removed at an anvil? (Disable message by setting to: null)
Message_Enchantment_Removed_Anvil: null

# What message should be displayed when an enchantment is removed when trading with a villager? (Disable message by setting to: null)
Message_Enchantment_Removed_Trade: "&5 Enchantment %enc not added!."



#********************************************************************************************************#
#*****************************************  Level Limit Customization  **************************************#

#This plugin can work in two ways:

#Firstly, you can simply use this plugin to limit the level of an enchantment to something lower than that which is normal in vanilla minecraft,
#for example you might want to stop players from getting the best efficiency 5 enchantment so you could limit DIG_SPEED to, say, 2 - meaning that
#any efficiency enchantment that is higher than 2 will be changed to 2 making this the new maximum efficiency enchantment level.

#Secondly, you can use this plugin to actually increase the level of an enchantment to something higher than that which is normal in vanilla minecraft
#For example you might want to allow certain players (they need the permission) to get an efficiency 10 enchantment which is double what
#is normally possible in minecraft. In this case you would set DIG_SPEED to 10, the player will then have a chance of getting anywhere between
#efficiency 5 (the vanilla amount) and efficiency 10. The chance is the likelihood of each level increase out of 100, so 50 is a 50% chance of an increase
#for each additional level whereas 100 would be a guarantee of always increasing to the maximum possible value(in this case efficiency 10).

#Armour Enchantments
PROTECTION_ENVIRONMENTAL: 1
PROTECTION_ENVIRONMENTAL_Chance: 100

PROTECTION_FIRE: 4
PROTECTION_FIRE_Chance: 100

PROTECTION_FALL: 4
PROTECTION_FALL_Chance: 100

PROTECTION_EXPLOSIONS: 4
PROTECTION_EXPLOSIONS_Chance: 100

PROTECTION_PROJECTILE: 4
PROTECTION_PROJECTILE_Chance: 100

FROST_WALKER: 2
FROST_WALKER_Chance: 100

OXYGEN: 3
OXYGEN_Chance: 100

WATER_WORKER: 1
WATER_WORKER_Chance: 100

THORNS: 3
THORNS_Chance: 100

DEPTH_STRIDER: 3
DEPTH_STRIDER_Chance: 100

#Weapon Enchantments
DAMAGE_ALL: 5
DAMAGE_ALL_Chance: 100

DAMAGE_UNDEAD: 5
DAMAGE_UNDEAD_Chance: 100

DAMAGE_ARTHROPODS: 5
DAMAGE_ARTHROPODS_Chance: 100

KNOCKBACK: 2
KNOCKBACK_Chance: 100

FIRE_ASPECT: 2
FIRE_ASPECT_Chance: 100

LOOT_BONUS_MOBS: 3
LOOT_BONUS_MOBS_Chance: 100

#Tool Enchantments
DIG_SPEED: 5
DIG_SPEED_Chance: 100

SILK_TOUCH: 1
SILK_TOUCH_Chance: 100

LOOT_BONUS_BLOCKS: 3
LOOT_BONUS_BLOCKS_Chance: 100

#Bow Enchantments
ARROW_DAMAGE: 5
ARROW_DAMAGE_Chance: 100

ARROW_KNOCKBACK: 2
ARROW_KNOCKBACK_Chance: 100

ARROW_FIRE: 1
ARROW_FIRE_Chance: 100

ARROW_INFINITE: 1
ARROW_INFINITE_Chance: 100

#Fishing Rod Enchantments
LUCK: 3
LUCK_Chance: 100

LURE: 3
LURE_Chance: 100

#Universal Enchantments
DURABILITY: 3
DURABILITY_Chance: 100

MENDING: 1
MENDING_Chance: 100
