plot:
  aliases:
  - plot
  - plots
  - p
  - plotsquared
  - plot2
  - p2
  - ps
  - '2'
  - plotme
  - plotz
  - ap
  usage: ''
  description: ''
  confirmation: false
buy:
  aliases:
  - buy
  usage: /plots buy
  description: Buy the plot you are standing on
  confirmation: false
save:
  aliases:
  - save
  - backup
  usage: ''
  description: Save your plot
  confirmation: false
load:
  aliases:
  - load
  - restore
  usage: /plots restore
  description: Load your plot
  confirmation: false
confirm:
  aliases:
  - confirm
  usage: ''
  description: Confirm an action
  confirmation: false
template:
  aliases:
  - template
  usage: /plots template [import|export] <world> <template>
  description: Create or use a world template
  confirmation: false
download:
  aliases:
  - download
  - dl
  usage: /plots download [schematic|bo3|world]
  description: Download your plot
  confirmation: false
changelog:
  aliases:
  - changelog
  - cl
  usage: /plots changelog
  description: View the changelog
  confirmation: false
setup:
  aliases:
  - setup
  - create
  usage: /plots setup
  description: Setup wizard for plot worlds
  confirmation: false
area:
  aliases:
  - area
  - world
  usage: /plots area <create|info|list|tp|regen>
  description: Create a new PlotArea
  confirmation: true
debugsavetest:
  aliases:
  - debugsavetest
  usage: /plots debugsavetest
  description: This command will force the recreation of all plots in the DB
  confirmation: false
debugloadtest:
  aliases:
  - debugloadtest
  usage: /plots debugloadtest
  description: This debug command will force the reload of all plots in the DB
  confirmation: false
createroadschematic:
  aliases:
  - createroadschematic
  - crs
  usage: /plots createroadschematic
  description: Add a road schematic to your world using the roads around your current
    plot
  confirmation: false
debugallowunsafe:
  aliases:
  - debugallowunsafe
  usage: /plots debugallowunsafe
  description: Allow unsafe actions until toggled off
  confirmation: false
regenallroads:
  aliases:
  - regenallroads
  - rgar
  usage: /plots regenallroads <world> [height]
  description: Regenerate all roads in the map using the set road schematic
  confirmation: false
claim:
  aliases:
  - claim
  - c
  usage: /plots claim
  description: Claim the current plot you're standing on
  confirmation: false
auto:
  aliases:
  - auto
  - a
  usage: /plots auto [length,width]
  description: Claim the nearest plot
  confirmation: false
visit:
  aliases:
  - visit
  - v
  - tp
  - teleport
  - goto
  - home
  - h
  usage: /plots visit [<player>|<alias>|<world>|<id>] [#]
  description: Visit someones plot
  confirmation: false
set:
  aliases:
  - set
  - s
  usage: /plots set <biome|alias|home|flag> <value...>
  description: Set a plot value
  confirmation: false
clear:
  aliases:
  - clear
  - reset
  usage: /plots clear
  description: Clear a plot
  confirmation: true
delete:
  aliases:
  - delete
  - dispose
  - del
  - reset
  usage: /plots delete
  description: Delete a plot
  confirmation: true
trust:
  aliases:
  - trust
  - t
  usage: /plots trust <player>
  description: Allow a player to build in a plot
  confirmation: false
add:
  aliases:
  - add
  usage: /plots add <player>
  description: Allow a user to build while you are online
  confirmation: false
leave:
  aliases:
  - leave
  usage: ''
  description: Leave a plot
  confirmation: false
deny:
  aliases:
  - deny
  - d
  - ban
  usage: /plots deny <player>
  description: Deny a user from a plot
  confirmation: false
remove:
  aliases:
  - remove
  - r
  - untrust
  - ut
  - undeny
  - unban
  - ud
  usage: /plots remove <player>
  description: Remove a player from a plot
  confirmation: false
info:
  aliases:
  - info
  - i
  usage: /plots info <id>
  description: Display plot info
  confirmation: false
near:
  aliases:
  - near
  - n
  usage: /plots near
  description: Display nearby players
  confirmation: false
list:
  aliases:
  - list
  - l
  - find
  - search
  usage: /plots list <forsale|mine|shared|world|top|all|unowned|unknown|player|world|done|fuzzy
    <search...>> [#]
  description: List plots
  confirmation: false
debug:
  aliases:
  - debug
  usage: /plots debug [msg]
  description: Show debug information
  confirmation: false
schematic:
  aliases:
  - schematic
  - sch
  usage: /plots schematic <arg...>
  description: Schematic command
  confirmation: false
plugin:
  aliases:
  - plugin
  - version
  usage: ''
  description: Show plugin information
  confirmation: false
purge:
  aliases:
  - purge
  usage: /plots purge world:<world> area:<area> id:<id> owner:<owner> shared:<shared>
    unknown:[true|false]
  description: Purge all plots for a world
  confirmation: true
reload:
  aliases:
  - reload
  usage: /plots reload
  description: Reload configurations
  confirmation: false
relight:
  aliases:
  - relight
  usage: ''
  description: Relight your plot
  confirmation: false
merge:
  aliases:
  - merge
  - m
  usage: /plots merge <all|n|e|s|w> [removeroads]
  description: Merge the plot you are standing on, with another plot
  confirmation: true
debugpaste:
  aliases:
  - debugpaste
  - dp
  usage: /plots debugpaste
  description: Upload settings.yml, worlds.yml, commands.yml and latest.log to www.hastebin.com
  confirmation: false
unlink:
  aliases:
  - unlink
  - u
  - unmerge
  usage: /plots unlink
  description: Unlink a mega-plot
  confirmation: true
kick:
  aliases:
  - kick
  - k
  usage: <player>
  description: Kick a player from your plot
  confirmation: false
rate:
  aliases:
  - rate
  - rt
  usage: /plots rate [#|next|purge]
  description: Rate the plot
  confirmation: false
debugclaimtest:
  aliases:
  - debugclaimtest
  usage: ''
  description: If you accidentally delete your database, this command will attempt
    to restore all plots based on the data from plot signs. Execution time may vary
  confirmation: false
inbox:
  aliases:
  - inbox
  usage: /plots inbox [inbox] [delete <index>|clear|page]
  description: Review the comments for a plot
  confirmation: false
comment:
  aliases:
  - comment
  - msg
  usage: ''
  description: Comment on a plot
  confirmation: false
database:
  aliases:
  - database
  - convert
  usage: /plots database [area] <sqlite|mysql|import>
  description: Convert/Backup Storage
  confirmation: false
swap:
  aliases:
  - swap
  - switch
  usage: /plots swap <X;Z>
  description: Swap two plots
  confirmation: false
music:
  aliases:
  - music
  usage: /plots music
  description: Player music in a plot
  confirmation: false
debugroadregen:
  aliases:
  - debugroadregen
  usage: /plots debugroadregen
  description: Regenerate all roads based on the road schematic
  confirmation: false
debugexec:
  aliases:
  - debugexec
  - exec
  - $
  usage: ''
  description: Mutli-purpose debug command
  confirmation: false
setflag:
  aliases:
  - setflag
  - f
  - flag
  - setf
  - setflag
  usage: /plots flag <set|remove|add|list|info> <flag> <value>
  description: Set plot flags
  confirmation: false
target:
  aliases:
  - target
  usage: /plots target <<plot>|nearest>
  description: Target a plot with your compass
  confirmation: false
debugfixflags:
  aliases:
  - debugfixflags
  usage: /plots debugfixflags <world>
  description: Attempt to fix all flags for a world
  confirmation: false
move:
  aliases:
  - move
  - debugmove
  usage: /plots move <X;Z>
  description: Move a plot
  confirmation: false
condense:
  aliases:
  - condense
  usage: ''
  description: Condense a plotworld
  confirmation: false
copy:
  aliases:
  - copy
  - copypaste
  usage: /plots copy <X;Z>
  description: Copy a plot
  confirmation: false
chat:
  aliases:
  - chat
  usage: /plots chat [on|off]
  description: Toggle plot chat on or off
  confirmation: false
trim:
  aliases:
  - trim
  usage: /plots trim <world> [regenerate]
  description: Delete unmodified portions of your plotworld
  confirmation: false
done:
  aliases:
  - done
  - submit
  usage: ''
  description: Mark a plot as done
  confirmation: false
continue:
  aliases:
  - continue
  usage: ''
  description: Continue a plot that was previously marked as done
  confirmation: false
bo3:
  aliases:
  - bo3
  - bo2
  usage: ''
  description: Mark a plot as done
  confirmation: false
middle:
  aliases:
  - middle
  - center
  - centre
  usage: /plots middle
  description: Teleports you to the center of the plot
  confirmation: false
grant:
  aliases:
  - grant
  usage: /plots grant <check|add> [player]
  description: ''
  confirmation: false
setowner:
  aliases:
  - setowner
  - owner
  - so
  - seto
  usage: /plots setowner <player>
  description: Set the plot owner
  confirmation: true
setdescription:
  aliases:
  - setdescription
  - desc
  - setdesc
  - setd
  - description
  usage: /plot desc <description>
  description: Set the plot description
  confirmation: false
setbiome:
  aliases:
  - setbiome
  - biome
  - sb
  - setb
  - b
  usage: /plots biome [biome]
  description: Set the plot biome
  confirmation: false
setalias:
  aliases:
  - setalias
  - alias
  - sa
  - name
  - rename
  - setname
  - seta
  - nameplot
  usage: /plots alias <set|remove> <alias>
  description: Set the plot name
  confirmation: false
sethome:
  aliases:
  - sethome
  - sh
  - seth
  usage: /plots sethome [none]
  description: Set the plot home
  confirmation: false
cluster:
  aliases:
  - cluster
  - clusters
  usage: ''
  description: Manage a plot cluster
  confirmation: false
debugimportworlds:
  aliases:
  - debugimportworlds
  usage: ''
  description: Import worlds by player name
  confirmation: false
toggle:
  aliases:
  - toggle
  - attribute
  usage: ''
  description: Toggle per user settings
  confirmation: false
  worldedit:
    aliases:
    - worldedit
    - we
    - wea
    usage: ''
    description: Toggle worldedit area restrictions
    confirmation: false
  titles:
    aliases:
    - titles
    usage: ''
    description: Toggle plot title messages
    confirmation: false
  chatspy:
    aliases:
    - chatspy
    - spy
    usage: ''
    description: Toggle admin chat spying
    confirmation: false
  clear-confirmation:
    aliases:
    - clear-confirmation
    usage: ''
    description: Toggle autoclear confirmation
    confirmation: false
  chat:
    aliases:
    - chat
    usage: ''
    description: Toggle plot chat
    confirmation: false
help:
  aliases:
  - help
  - he
  - '?'
  usage: help [category|#]
  description: Get this help menu
  confirmation: false
uuidconvert:
  aliases:
  - uuidconvert
  usage: /plots uuidconvert <lower|offline|online>
  description: Debug UUID conversion
  confirmation: false
weanywhere:
  aliases:
  - weanywhere
  - wea
  usage: /plots weanywhere
  description: Force bypass of WorldEdit
  confirmation: false
trimchunks:
  aliases:
  - trimchunks
  usage: /plots trimchunks <world> <boolean-delete-unowned>
  description: Delete unmodified portions of your plotworld
  confirmation: false
generatebiome:
  aliases:
  - generatebiome
  - bg
  - gb
  usage: /plots generatebiome <biome>
  description: Generate a biome in your plot
  confirmation: false
moveto512:
  aliases:
  - moveto512
  usage: /plots moveto512 [world]
  description: Move plots to a 512 sized region
  confirmation: false
